#!/usr/bin/env bash
# Generate a minimal BoostConfig.cmake that points at the system boost headers.
#
# Background: Ubuntu's libboost-dev ships only headers — no BoostConfig.cmake.
# CMake 3.30+ removed the FindBoost.cmake module (CMP0167), so
# find_package(Boost) fails with:
#     Could NOT find Boost (missing: Boost_INCLUDE_DIR)
#
# This script writes a hand-rolled BoostConfig.cmake + BoostConfigVersion.cmake
# into <prefix>/lib/cmake/Boost/ and <prefix>/lib/cmake/Boost-<version>/.
# libtorrent's `find_package(Boost REQUIRED)` will then succeed.
#
# Usage:
#   ./ci/make-boost-config.sh <prefix> [boost_include_dir]
#
# Defaults:
#   boost_include_dir = /usr/include

set -euo pipefail

PREFIX="${1:?usage: make-boost-config.sh <prefix> [boost_include_dir]}"
BOOST_INC_DIR="${2:-/usr/include}"

if [ ! -f "${BOOST_INC_DIR}/boost/version.hpp" ]; then
    echo "ERROR: ${BOOST_INC_DIR}/boost/version.hpp not found." >&2
    echo "       Is libboost-dev installed?" >&2
    exit 1
fi

# Boost_VERSION is e.g. 108300 for 1.83.0
# Encoding: MAJOR*100000 + MINOR*100 + SUBMINOR
BOOST_VERSION=$(grep -E '^#define BOOST_VERSION ' "${BOOST_INC_DIR}/boost/version.hpp" | awk '{print $3}')
BOOST_MAJOR=$((BOOST_VERSION / 100000))
BOOST_MINOR=$(((BOOST_VERSION / 100) % 100))
BOOST_SUBMINOR=$((BOOST_VERSION % 100))
BOOST_VER_DOTTED="${BOOST_MAJOR}.${BOOST_MINOR}.${BOOST_SUBMINOR}"

echo "Detected Boost ${BOOST_VER_DOTTED} (${BOOST_VERSION}) at ${BOOST_INC_DIR}/boost"

# Both "Boost" and "Boost-<version>" directories are populated — CMake's
# find_package accepts either form.
for dir in "Boost" "Boost-${BOOST_VER_DOTTED}"; do
    outdir="${PREFIX}/lib/cmake/${dir}"
    mkdir -p "${outdir}"

    cat > "${outdir}/BoostConfig.cmake" <<EOF
# Auto-generated by ci/make-boost-config.sh
# Minimal Boost config — headers only.
# Since Boost 1.69, asio/system are header-only and don't need compiled libs.

set(Boost_INCLUDE_DIRS "${BOOST_INC_DIR}")
set(Boost_INCLUDE_DIR  "${BOOST_INC_DIR}")
set(Boost_VERSION ${BOOST_VERSION})
set(Boost_MAJOR_VERSION ${BOOST_MAJOR})
set(Boost_MINOR_VERSION ${BOOST_MINOR})
set(Boost_SUBMINOR_VERSION ${BOOST_SUBMINOR})

if(NOT TARGET Boost::headers)
    add_library(Boost::headers INTERFACE IMPORTED)
    set_target_properties(Boost::headers PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${BOOST_INC_DIR}")
endif()

if(NOT TARGET Boost::system)
    add_library(Boost::system INTERFACE IMPORTED)
    target_link_libraries(Boost::system INTERFACE Boost::headers)
endif()

if(NOT TARGET Boost::disable_autolinking)
    add_library(Boost::disable_autolinking INTERFACE IMPORTED)
endif()
EOF

    cat > "${outdir}/BoostConfigVersion.cmake" <<EOF
# Auto-generated by ci/make-boost-config.sh
set(PACKAGE_VERSION "${BOOST_VER_DOTTED}")
if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
        set(PACKAGE_VERSION_EXACT TRUE)
    endif()
endif()
EOF
done

echo "Wrote BoostConfig.cmake to:"
echo "  ${PREFIX}/lib/cmake/Boost/"
echo "  ${PREFIX}/lib/cmake/Boost-${BOOST_VER_DOTTED}/"
